/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rolando Villca' at '2/19/16 8:40 AM' with Gradle 2.11
 *
 * @author Rolando Villca, @date 2/19/16 8:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
